apiVersion: v1
kind: ConfigMap
metadata:
  name: coworking-configmap
data:
  DB_NAME: mydatabase
  DB_USERNAME: myuser
  DB_HOST: postgresql-service
  DB_PORT: '5432'

---

apiVersion: v1
kind: Secret
metadata:
  name: coworking-secret
type: Opaque
data:
  DB_PASSWORD: bXlwYXNzd29yZA==